### ISSUE TITLE
Events html page

### ISSUE THREAD

**Issue by leranf** [urgentSloth/urgentSloth#25]

**Comment by pavelmp** [comment]
https://www.yelp.com/developers/api_console

**Comment by pavelmp** [comment]
{
            "is_claimed": true, 
            "rating": 4.5, 
            "mobile_url": "http://m.yelp.com/biz/tadu-ethiopian-kitchen-san-francisco-3?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=gsjk0o7MGSveWE1fl3XDJQ", 
            "rating_img_url": "http://s3-media2.fl.yelpcdn.com/assets/2/www/img/99493c12711e/ico/stars/v1/stars_4_half.png", 
            "review_count": 261, 
            "name": "Tadu Ethiopian Kitchen", 
            "rating_img_url_small": "http://s3-media2.fl.yelpcdn.com/assets/2/www/img/a5221e66bc70/ico/stars/v1/stars_small_4_half.png", 
            "url": "http://www.yelp.com/biz/tadu-ethiopian-kitchen-san-francisco-3?utm_campaign=yelp_api&utm_medium=api_v2_search&utm_source=gsjk0o7MGSveWE1fl3XDJQ", 
            "categories": [
                [
                    "Ethiopian", 
                    "ethiopian"
                ]
            ], 
            "menu_date_updated": 1442230237, 
            "phone": "4154096649", 
            "snippet_text": "Embarrassing admission time. I really, really love kitfo. I might love it as much as I love my SO. I've ordered kitfo in like five different countries...", 
            "image_url": "http://s3-media4.fl.yelpcdn.com/bphoto/ClnhSWG3puv1_NsL3retiw/ms.jpg", 
            "snippet_image_url": "http://s3-media4.fl.yelpcdn.com/photo/3UEsuC6dzHatxrI3a-C1_g/ms.jpg", 
            "display_phone": "+1-415-409-6649", 
            "rating_img_url_large": "http://s3-media4.fl.yelpcdn.com/assets/2/www/img/9f83790ff7f6/ico/stars/v1/stars_large_4_half.png", 
            "menu_provider": "single_platform", 
            "id": "tadu-ethiopian-kitchen-san-francisco-3", 
            "is_closed": false, 
            "location": {
                "cross_streets": "Jones St & Leavenworth St", 
                "city": "San Francisco", 
                "display_address": [
                    "484 Ellis St", 
                    "Tenderloin", 
                    "San Francisco, CA 94102"
                ], 
                "geo_accuracy": 9.5, 
                "neighborhoods": [
                    "Tenderloin"
                ], 
                "postal_code": "94102", 
                "country_code": "US", 
                "address": [
                    "484 Ellis St"
                ], 
                "coordinate": {
                    "latitude": 37.7847191, 
                    "longitude": -122.414172
                }, 
                "state_code": "CA"
            }
        }
